apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-a-2329208
  labels:
    app: devops-a-2329208
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-a-2329208
  template:
    metadata:
      labels:
        app: devops-a-2329208
    spec:
      containers:
      - name: devops-a-2329208
        image: devops-a-2329208:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
